apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rec-dep
  name: rec-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rec
  template:
    metadata:
      labels:
        app: rec
    spec:
      serviceAccountName: aws-bedrock
      containers:
        - image: 178020491921.dkr.ecr.ap-northeast-2.amazonaws.com/recommend:22
          name: recommend
          command: ["python", "recommend.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: recommend-svc
spec:
  selector:
    app: rec
  ports:
    - port: 5000
      targetPort: 5000
